version: "3.3"
services:
  database:
    image: postgres
    container_name: postgres_ignite
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/home/app
      - /home/app/node_modules
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
